rootfs/etc/init.d/hwinfo: check presence of sdb-read before calling it
If the build or image is broken and sdb-read is missing don't try to
overwrite hwinfo

Signed-off-by: Adam Wujek <adam.wujek@cern.ch>

diff --git a/userspace/rootfs_override/etc/init.d/hwinfo b/userspace/rootfs_override/etc/init.d/hwinfo
--- a/userspace/rootfs_override/etc/init.d/hwinfo
+++ b/userspace/rootfs_override/etc/init.d/hwinfo
@@ -21,6 +21,14 @@ if ! grep -q hwinfo /proc/mtd; then
     exit 0;
 fi
 
+if ! [ -f /wr/bin/sdb-read ]; then
+    # If for some reason sdb-read is not available, don't touch hwinfo
+    echo "/wr/bin/sdb-read not available!"
+    # save script result for snmp
+    echo "hwinfo_error" > /tmp/hwinfo_read_status
+    exit 0;
+fi
+
 # Is there sdb in there? If so, nothing to do.
 if /wr/bin/sdb-read /dev/mtd5ro > /dev/null; then
     # save script result for snmp
