[BUG: #211] rootfs/etc/init.d/snmpd: wait 60 seconds in background
Delay monit start by extra 60 seconds.

The delay of snmpd start was put into background because /etc/init.d/rcK
cannot be started before /etc/init.d/rcS is finished. Such behavior is
implemented in the init.

Signed-off-by: Adam Wujek <dev_public@wujek.eu>

diff --git a/userspace/rootfs_override/etc/init.d/snmpd b/userspace/rootfs_override/etc/init.d/snmpd
--- a/userspace/rootfs_override/etc/init.d/snmpd
+++ b/userspace/rootfs_override/etc/init.d/snmpd
@@ -16,6 +16,22 @@ start_counter() {
 	echo "$START_COUNTER" > $COUNTER_FILE
 }
 
+snmpd_start() {
+    # Log source address (-a)
+    start-stop-daemon -q -p $SNMP_PID -S \
+		--exec /usr/sbin/snmpd -- $LOG -p $SNMP_PID -a -c $SNMP_CONF
+
+    ret=$?
+    if [ $ret -eq 0 ]; then
+	start_counter
+	echo "OK"
+    elif [ $ret -eq 1 ]; then
+	echo "Failed (already running?)"
+    else
+	echo "Failed"
+    fi
+}
+
 start() {
     echo -n "Starting snmpd daemon: "
 
@@ -42,22 +58,13 @@ start() {
         # file doesn't exist yet so it's a boot call, delay to avoid spurious
 	# errors
 	echo "Delaying the start of snmp daemon"
-	sleep 60
+	{ sleep 60; snmpd_start; } &
+	return
     fi
 
-    # Log source address (-a)
-    start-stop-daemon -q -p $SNMP_PID -S \
-		--exec /usr/sbin/snmpd -- $LOG -p $SNMP_PID -a -c $SNMP_CONF
+    # start snmpd without delay
+    snmpd_start
 
-    ret=$?
-    if [ $ret -eq 0 ]; then
-	start_counter
-	echo "OK"
-    elif [ $ret -eq 1 ]; then
-	echo "Failed (already running?)"
-    else
-	echo "Failed"
-    fi
 }
 
 stop() {
